export enum TipoMovimientoPresupuesto {
  ASIGNACION_INICIAL = 'ASIGNACION_INICIAL',
  COMPROMISO = 'COMPROMISO',
  EJERCICIO = 'EJERCICIO',
  LIBERACION_COMPROMISO = 'LIBERACION_COMPROMISO',
  LIBERACION_EJERCICIO = 'LIBERACION_EJERCICIO',
  AJUSTE_MANUAL = 'AJUSTE_MANUAL', // Agrupa ampliaciones y reducciones aquí
}
